version: '3.4'
services:
  web:
    build:
      network: host
      context: .
    container_name: tennis
    volumes:
      - ./static:/static
      - ./app:/data/app
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_tennis
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
