# Generated by Django 2.2.5 on 2019-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190927_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_since',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
