# Generated by Django 2.2.5 on 2019-10-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
