# Generated by Django 2.2.5 on 2019-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191021_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='', upload_to='users/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='court',
            name='image',
            field=models.ImageField(upload_to='courts/'),
        ),
    ]
