# Generated by Django 2.2.5 on 2019-11-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message_is_read'),
        ('app', '0012_auto_20191024_1916'),
    ]

    operations = [
    ]
