# Generated by Django 2.2.5 on 2019-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191120_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_court_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(),
        ),
    ]
